# .github/workflows/monthly_twitter_report.yml
name: Monthly Twitter Report       # ← renamed

on:
  # Manual trigger from the Actions tab
  workflow_dispatch:

  # Run at 03:00 UTC on the *first* day of every month
  schedule:
    - cron: "0 3 1 * *"            # min hr dom mon dow

jobs:
  build-run:
    runs-on: ubuntu-latest

    # ------------------------------------------------------------------
    # Environment variables – pulled from GitHub Secrets / Org Vars
    # ------------------------------------------------------------------
    env:
      # ---------- Supabase ----------
      SUPABASE_HOST:         ${{ secrets.SUPABASE_HOST }}
      SUPABASE_PORT:         ${{ secrets.SUPABASE_PORT }}
      SUPABASE_DB:           ${{ secrets.SUPABASE_DB }}
      SUPABASE_USER:         ${{ secrets.SUPABASE_USER }}
      SUPABASE_PWD:          ${{ secrets.SUPABASE_PWD }}
      SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      SB_BUCKET:             ${{ vars.SB_BUCKET }}   # e.g. **monthly-reports**

      # ---------- OpenAI ----------
      OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}

      # ---------- Mailjet ----------
      MJ_API_KEY:            ${{ secrets.MJ_API_KEY }}
      MJ_API_SECRET:         ${{ secrets.MJ_API_SECRET }}
      MAIL_FROM:             ${{ vars.MAIL_FROM }}
      MAIL_TO:               ${{ vars.MAIL_TO }}

      CI: true
      R_KEEP_PKG_SOURCE: no   # make installs non‑interactive

    steps:
      - name: Checkout repo                         # 1
        uses: actions/checkout@v4

      - name: Set up R                              # 2
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up Pandoc                         # 3
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install headless Chrome               # 4
        uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          chrome-version: stable

      - name: Install system libraries              # 5
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1 libharfbuzz-dev libfribidi-dev \
            libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Install R package dependencies        # 6
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::lubridate
            any::httr2
            any::httr
            any::jsonlite
            any::glue
            any::pagedown
            any::RPostgres
            any::DBI
            any::base64enc
            any::tidytext

      - name: Confirm Chrome path (debug)           # 7
        run: |
          echo "CHROME_BIN -> $CHROME_BIN"
          Rscript -e 'cat("pagedown::find_chrome() ->", pagedown::find_chrome(), "\n")'

      - name: Run report script                     # 8
        run: Rscript generate_report.R

      - name: Upload generated artefacts (always)   # 9
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monthly-report-artifacts
          path: |
            summary.md
            summary_full.pdf
          if-no-files-found: warn
