name: Monthly Twitter Report

on:
  workflow_dispatch:
  # At 03:00 UTC on the first day of every month
  schedule:
    - cron: "0 3 1 * *"

jobs:
  build-run:
    runs-on: ubuntu-latest

    env:
      # ---------- Supabase ----------
      SUPABASE_HOST:         ${{ secrets.SUPABASE_HOST }}
      SUPABASE_PORT:         ${{ secrets.SUPABASE_PORT }}
      SUPABASE_DB:           ${{ secrets.SUPABASE_DB }}
      SUPABASE_USER:         ${{ secrets.SUPABASE_USER }}
      SUPABASE_PWD:          ${{ secrets.SUPABASE_PWD }}
      SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      SB_BUCKET:             ${{ vars.SB_BUCKET || 'monthly-reports' }}

      # ---------- OpenAI ----------
      OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}

      # ---------- Mailjet (kept, but emailing is OFF unless SEND_EMAIL=true) ----------
      MJ_API_KEY:            ${{ secrets.MJ_API_KEY }}
      MJ_API_SECRET:         ${{ secrets.MJ_API_SECRET }}
      MAIL_FROM:             ${{ vars.MAIL_FROM }}
      MAIL_TO:               ${{ vars.MAIL_TO }}

      # Turn email on/off
      SEND_EMAIL:            "false"

      CI: true
      R_KEEP_PKG_SOURCE: no

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # Install Chrome and capture its path
      - name: Install headless Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          chrome-version: stable

      # Expose Chrome path to the rest of the job
      - name: Export CHROME_BIN
        run: echo "CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV

      # Optional: also set CHROMOTE_CHROME
      - name: Export CHROMOTE_CHROME
        run: echo "CHROMOTE_CHROME=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV

      - name: Install system libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1 libharfbuzz-dev libfribidi-dev \
            libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev \
            libnss3 libxss1

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::lubridate
            any::httr2
            any::httr
            any::jsonlite
            any::glue
            any::pagedown
            any::RPostgres
            any::DBI
            any::base64enc
            any::tidytext
            any::magrittr

      - name: Confirm Chrome path (debug)
        run: |
          echo "CHROME_BIN -> $CHROME_BIN"
          "$CHROME_BIN" --version || true
          Rscript -e 'cat("pagedown::find_chrome() ->", pagedown::find_chrome(), "\n")'

      - name: Run report script
        run: Rscript generate_report.R

      - name: Upload generated artefacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monthly-report-artifacts
          path: |
            summary.md
            summary_full.pdf
          if-no-files-found: warn

